name: AnimageImage
author: astolwijk
current: 1.1
category: Effects
tags: [Image,Animation,PNG]
demo: http://www.aryweb.nl/projects/animateimage/
docs: http://github.com/arian/animateImage/blob/master/README.md